mutation MAKE_A_BOOKING(
  $customerEmail: String
  $bookingDate: String
  $listingId: String
  $customers: [CustomerInput]
) {
  makeABooking(
    customerEmail: $customerEmail
    bookingDate: $bookingDate
    listingId: $listingId
    customers: $customers
  ) {
    bookingId
    listingID
    bookingDate
    size
    bookingTotal
    customerEmail
    customers {
      name
      surname
      country
      passportNumber
      physioScore
    }
    chargeReciept
  }
}
